import Foundation
import UIKit

/// High-level X (Twitter) API client. Wraps OAuth (delegated to `XAuth`) and
/// the v2 chunked media upload + tweet create flow.
///
/// Legacy v1.1 media endpoints were sunset June 9 2025; we use v2 exclusively.
///
/// Publish flow (see `publishShort`):
///   1. Download the MP4 to a temp file so we can chunk by offset.
///   2. `POST /2/media/upload/initialize`
///        body: { media_category: "tweet_video", media_type: "video/mp4",
///                total_bytes: <int> }
///        → { data: { id: "<media_id>", expires_after_secs } }
///   3. `POST /2/media/upload/:media_id/append` (one call per chunk, 4 MB each)
///        multipart/form-data fields:
///          - segment_index (form field, 0-based)
///          - media         (file field, chunk bytes)
///        → 200 with no body on success.
///   4. `POST /2/media/upload/:media_id/finalize` (no body)
///        → { data: { id, processing_info?: { state, check_after_secs?,
///                                             progress_percent? } } }
///        If `processing_info` is present, poll step 5.
///   5. `GET  /2/media/upload?command=STATUS&media_id=<id>` until state is
///        "succeeded" or "failed". Respects `check_after_secs`.
///   6. `POST /2/tweets`
///        body: { text: <caption+hashtags>, media: { media_ids: ["<id>"] } }
///        → { data: { id, text, edit_history_tweet_ids } }
///
/// Tweet URL is `https://twitter.com/<username>/status/<id>`.
///
/// Tweet text budget is 280 chars (`XConfig.maxTweetTextLength`). If the
/// body + hashtags exceed that, `buildTweetText(body:hashtags:)` trims the
/// body on word boundaries and appends as many full hashtags as fit. Never
/// cuts mid-word or mid-hashtag.
///
/// NOTE: X does NOT support custom video thumbnails via API. The first-frame
/// cover is auto-generated by X. We don't send `thumbnailData`.
///
/// Reference: research/2026-04-13-shorts-distribution-api-comparison.md §5.
@MainActor
final class XClient {
    enum ClientError: Error, LocalizedError {
        case notAuthorized
        case notConfigured
        case downloadFailed(URLError)
        case downloadStatus(Int)
        case fileSystem(String)
        case requestFailed(String, Int, String)
        case decodeFailed(String, Error)
        case missingResponseField(String)
        case mediaProcessingFailed(String)
        case mediaProcessingTimeout

        var errorDescription: String? {
            switch self {
            case .notAuthorized: return "Sign in with X first."
            case .notConfigured: return "X not configured. See docs/superpowers/setup/x-setup.md."
            case .downloadFailed(let err): return "Video download failed: \(err.localizedDescription)"
            case .downloadStatus(let code): return "Video download returned HTTP \(code)."
            case .fileSystem(let detail): return "File system error: \(detail)"
            case .requestFailed(let label, let code, let body):
                return "\(label) failed (HTTP \(code)): \(body)"
            case .decodeFailed(let label, let err):
                return "\(label) decode failed: \(err.localizedDescription)"
            case .missingResponseField(let field):
                return "X response missing expected field: \(field)"
            case .mediaProcessingFailed(let detail):
                return "X media processing failed: \(detail)"
            case .mediaProcessingTimeout:
                return "X media processing timed out. Retry in a moment."
            }
        }
    }

    /// Progress callback. Reports overall publish progress 0.0 → 1.0 spanning
    /// download (5%), initialize (5%), append chunks (75%), finalize + poll
    /// (10%), tweet create (5%).
    typealias ProgressHandler = @Sendable (Double) -> Void

    private let auth: XAuth

    init() {
        self.auth = XAuth()
    }

    init(auth: XAuth) {
        self.auth = auth
    }

    // MARK: - Authorization surface

    var isAuthorized: Bool {
        (try? TokenStore.x.load()) != nil
    }

    var currentTokens: XTokens? {
        try? TokenStore.x.load()
    }

    /// Run the full OAuth flow. Returns the resolved username.
    @discardableResult
    func authorize() async throws -> String {
        let tokens = try await auth.authorize()
        return tokens.username
    }

    func signOut() {
        TokenStore.x.clear()
    }

    /// Returns a token guaranteed fresh (refreshes if needed and possible).
    private func validAccessToken() async throws -> XTokens {
        guard let tokens = try TokenStore.x.load() else { throw ClientError.notAuthorized }
        if tokens.isFresh { return tokens }
        if tokens.refreshToken != nil {
            return try await auth.refresh(using: tokens)
        }
        throw ClientError.notAuthorized
    }

    // MARK: - Public publish entry point

    /// Downloads the MP4 from `videoURL`, uploads it via the v2 chunked media
    /// flow, polls processing until ready, then creates a tweet with the
    /// attached media. Returns the public tweet URL.
    func publishShort(
        videoURL: URL,
        caption: String,
        hashtags: [String],
        progress: ProgressHandler? = nil
    ) async throws -> URL {
        guard XConfig.isConfigured else { throw ClientError.notConfigured }
        var tokens = try await validAccessToken()

        progress?(0.0)

        // 1. Download MP4 to temp.
        let localFile = try await downloadVideo(from: videoURL)
        defer { try? FileManager.default.removeItem(at: localFile) }

        let attrs = try FileManager.default.attributesOfItem(atPath: localFile.path)
        guard let fileSize = (attrs[.size] as? NSNumber)?.int64Value, fileSize > 0 else {
            throw ClientError.fileSystem("Downloaded file has zero size")
        }
        progress?(0.05)

        // 2. Initialize.
        let mediaID = try await initializeMedia(
            totalBytes: fileSize,
            accessToken: &tokens
        )
        progress?(0.10)

        // 3. Append chunks.
        try await appendChunks(
            mediaID: mediaID,
            file: localFile,
            fileSize: fileSize,
            accessToken: &tokens,
            progress: { fraction in
                // Map chunked upload to overall 10% → 85%.
                progress?(0.10 + fraction * 0.75)
            }
        )

        // 4. Finalize — may return processing_info requiring polling.
        let initialProcessing = try await finalizeMedia(
            mediaID: mediaID,
            accessToken: &tokens
        )
        progress?(0.88)

        // 5. Poll STATUS if needed.
        if let info = initialProcessing {
            try await pollMediaStatus(
                mediaID: mediaID,
                initial: info,
                accessToken: &tokens
            )
        }
        progress?(0.95)

        // 6. Create tweet.
        let text = Self.buildTweetText(body: caption, hashtags: hashtags)
        let tweetID = try await createTweet(
            text: text,
            mediaID: mediaID,
            accessToken: &tokens
        )
        progress?(1.0)

        let username = tokens.username
        return URL(string: "https://twitter.com/\(username)/status/\(tweetID)")!
    }

    // MARK: - Tweet-text truncation

    /// Assembles body + hashtags into a tweet of at most
    /// `XConfig.maxTweetTextLength` characters. Truncation rules:
    ///   - If the full string (body + "\n\n" + hashtags) fits, return as-is.
    ///   - Otherwise, compute a budget for the body = total - hashtags - separator.
    ///     If the budget is negative or too small to be useful, drop hashtags
    ///     one at a time (from the end) until the body can fit.
    ///   - Cut the body on the last whitespace boundary that still fits; append
    ///     " …" to signal truncation.
    ///   - Never cut mid-word or mid-hashtag — hashtags are all-or-nothing.
    ///
    /// Public for testability.
    static func buildTweetText(body: String, hashtags: [String]) -> String {
        let max = XConfig.maxTweetTextLength
        let cleanBody = body.trimmingCharacters(in: .whitespacesAndNewlines)
        // Filter: require non-empty, preserve user's `#` prefix or add one.
        let tags = hashtags
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty }
            .map { $0.hasPrefix("#") ? $0 : "#\($0)" }

        // Try full-string fit first.
        let fullHashtagJoin = tags.joined(separator: " ")
        let full = joined(body: cleanBody, hashtagLine: fullHashtagJoin)
        if full.count <= max {
            return full
        }

        // Drop hashtags from the end until the body + remaining hashtags fit.
        var kept = tags
        while !kept.isEmpty {
            let hashLine = kept.joined(separator: " ")
            let sepLen = (cleanBody.isEmpty || hashLine.isEmpty) ? 0 : 2 // "\n\n"
            let budget = max - hashLine.count - sepLen
            if budget >= 10 {
                let truncated = truncateOnWord(cleanBody, maxChars: budget)
                return joined(body: truncated, hashtagLine: hashLine)
            }
            kept.removeLast()
        }

        // No hashtags fit — truncate body to the full budget.
        let truncated = truncateOnWord(cleanBody, maxChars: max)
        return truncated
    }

    private static func joined(body: String, hashtagLine: String) -> String {
        switch (body.isEmpty, hashtagLine.isEmpty) {
        case (true, true): return ""
        case (false, true): return body
        case (true, false): return hashtagLine
        case (false, false): return "\(body)\n\n\(hashtagLine)"
        }
    }

    /// Returns `s` truncated to at most `maxChars` characters, cut at the
    /// last whitespace before the limit (never mid-word). Appends " …" when
    /// truncation actually occurs. If the first word is already longer than
    /// `maxChars - 2`, returns the first `maxChars` characters as-is (rare —
    /// happens only with contiguous non-whitespace strings longer than the
    /// whole budget).
    private static func truncateOnWord(_ s: String, maxChars: Int) -> String {
        guard maxChars > 0 else { return "" }
        if s.count <= maxChars { return s }

        // Reserve 2 chars for " …" marker.
        let ellipsis = " …"
        let hardBudget = max(1, maxChars - ellipsis.count)

        let prefix = String(s.prefix(hardBudget))
        if let lastSpace = prefix.rangeOfCharacter(
            from: .whitespacesAndNewlines,
            options: .backwards
        ) {
            let trimmed = String(prefix[..<lastSpace.lowerBound])
                .trimmingCharacters(in: .whitespacesAndNewlines)
            if !trimmed.isEmpty {
                return "\(trimmed)\(ellipsis)"
            }
        }
        // Pathological: no whitespace in the prefix. Fall back to hard cut.
        return String(s.prefix(maxChars))
    }

    // MARK: - Download

    private func downloadVideo(from url: URL) async throws -> URL {
        let dest = FileManager.default.temporaryDirectory
            .appendingPathComponent("x-upload-\(UUID().uuidString).mp4")
        do {
            let (tempURL, response) = try await URLSession.shared.download(from: url)
            if let http = response as? HTTPURLResponse, !(200..<300).contains(http.statusCode) {
                throw ClientError.downloadStatus(http.statusCode)
            }
            try? FileManager.default.removeItem(at: dest)
            try FileManager.default.moveItem(at: tempURL, to: dest)
            return dest
        } catch let urlErr as URLError {
            throw ClientError.downloadFailed(urlErr)
        } catch let clientErr as ClientError {
            throw clientErr
        } catch {
            throw ClientError.fileSystem(error.localizedDescription)
        }
    }

    // MARK: - Initialize (step 2)

    private func initializeMedia(
        totalBytes: Int64,
        accessToken tokens: inout XTokens
    ) async throws -> String {
        let url = XConfig.apiBase.appendingPathComponent("media/upload/initialize")
        let body: [String: Any] = [
            "media_category": "tweet_video",
            "media_type": "video/mp4",
            "total_bytes": totalBytes,
        ]
        let data = try await authedJSONRequest(
            url: url,
            method: "POST",
            json: body,
            label: "media.initialize",
            accessToken: &tokens
        )
        guard let root = try JSONSerialization.jsonObject(with: data) as? [String: Any],
              let d = root["data"] as? [String: Any],
              let id = d["id"] as? String, !id.isEmpty else {
            throw ClientError.missingResponseField("data.id")
        }
        return id
    }

    // MARK: - Append chunks (step 3)

    private func appendChunks(
        mediaID: String,
        file: URL,
        fileSize: Int64,
        accessToken tokens: inout XTokens,
        progress: @escaping @Sendable (Double) -> Void
    ) async throws {
        let chunkSize = XConfig.mediaUploadChunkSize
        let handle = try FileHandle(forReadingFrom: file)
        defer { try? handle.close() }

        var segmentIndex = 0
        var offset: Int64 = 0

        let url = XConfig.apiBase.appendingPathComponent("media/upload/\(mediaID)/append")

        while offset < fileSize {
            try handle.seek(toOffset: UInt64(offset))
            let remaining = Int(min(Int64(chunkSize), fileSize - offset))
            let chunk = try handle.read(upToCount: remaining) ?? Data()
            if chunk.isEmpty { break }

            try await postAppendChunk(
                url: url,
                segmentIndex: segmentIndex,
                chunk: chunk,
                accessToken: &tokens
            )

            offset += Int64(chunk.count)
            segmentIndex += 1

            let fraction = min(1.0, Double(offset) / Double(fileSize))
            progress(fraction)
        }
    }

    private func postAppendChunk(
        url: URL,
        segmentIndex: Int,
        chunk: Data,
        accessToken tokens: inout XTokens
    ) async throws {
        let boundary = "Boundary-\(UUID().uuidString)"
        let body = Self.multipartBody(
            boundary: boundary,
            fields: [("segment_index", String(segmentIndex))],
            fileField: (name: "media", filename: "chunk.bin", contentType: "application/octet-stream", data: chunk)
        )

        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.setValue("Bearer \(tokens.accessToken)", forHTTPHeaderField: "Authorization")
        request.setValue("multipart/form-data; boundary=\(boundary)", forHTTPHeaderField: "Content-Type")
        request.httpBody = body

        let (data, response) = try await URLSession.shared.data(for: request)
        guard let http = response as? HTTPURLResponse else {
            throw ClientError.requestFailed("media.append", -1, "No HTTP response")
        }

        // Auto-refresh on 401, retry once.
        if http.statusCode == 401, tokens.refreshToken != nil {
            tokens = try await auth.refresh(using: tokens)
            request.setValue("Bearer \(tokens.accessToken)", forHTTPHeaderField: "Authorization")
            let (data2, response2) = try await URLSession.shared.data(for: request)
            guard let http2 = response2 as? HTTPURLResponse, (200..<300).contains(http2.statusCode) else {
                let code = (response2 as? HTTPURLResponse)?.statusCode ?? -1
                let bodyStr = String(data: data2, encoding: .utf8) ?? "<non-utf8>"
                throw ClientError.requestFailed("media.append (retry)", code, bodyStr)
            }
            return
        }

        guard (200..<300).contains(http.statusCode) else {
            let bodyStr = String(data: data, encoding: .utf8) ?? "<non-utf8>"
            throw ClientError.requestFailed("media.append[\(segmentIndex)]", http.statusCode, bodyStr)
        }
    }

    // MARK: - Finalize (step 4)

    /// Result of finalize. `nil` means media is ready immediately (no
    /// processing required). Otherwise caller polls STATUS.
    private struct ProcessingInfo {
        let state: String
        let checkAfterSecs: Int
        let progressPercent: Int?
        let errorDetail: String?
    }

    private func finalizeMedia(
        mediaID: String,
        accessToken tokens: inout XTokens
    ) async throws -> ProcessingInfo? {
        let url = XConfig.apiBase.appendingPathComponent("media/upload/\(mediaID)/finalize")
        let data = try await authedJSONRequest(
            url: url,
            method: "POST",
            json: nil,
            label: "media.finalize",
            accessToken: &tokens
        )
        return Self.parseProcessingInfo(from: data)
    }

    // MARK: - Poll STATUS (step 5)

    private func pollMediaStatus(
        mediaID: String,
        initial: ProcessingInfo,
        accessToken tokens: inout XTokens
    ) async throws {
        var info = initial
        // Hard ceiling on total polling time: 3 minutes.
        let deadline = Date().addingTimeInterval(180)

        while true {
            switch info.state.lowercased() {
            case "succeeded":
                return
            case "failed":
                throw ClientError.mediaProcessingFailed(info.errorDetail ?? "state=failed")
            default:
                break // pending / in_progress
            }

            if Date() >= deadline {
                throw ClientError.mediaProcessingTimeout
            }

            let wait = max(1, info.checkAfterSecs)
            try await Task.sleep(nanoseconds: UInt64(wait) * 1_000_000_000)

            var components = URLComponents(
                url: XConfig.apiBase.appendingPathComponent("media/upload"),
                resolvingAgainstBaseURL: false
            )!
            components.queryItems = [
                URLQueryItem(name: "command", value: "STATUS"),
                URLQueryItem(name: "media_id", value: mediaID),
            ]
            let data = try await authedGetRequest(
                url: components.url!,
                label: "media.status",
                accessToken: &tokens
            )
            guard let next = Self.parseProcessingInfo(from: data) else {
                // No processing_info after STATUS → assume succeeded.
                return
            }
            info = next
        }
    }

    private static func parseProcessingInfo(from data: Data) -> ProcessingInfo? {
        guard let root = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let d = root["data"] as? [String: Any],
              let proc = d["processing_info"] as? [String: Any],
              let state = proc["state"] as? String else {
            return nil
        }
        let check = (proc["check_after_secs"] as? Int) ?? 1
        let pct = proc["progress_percent"] as? Int
        // Error can be `{ error: { name, message } }`.
        var errorDetail: String?
        if let errorObj = proc["error"] as? [String: Any] {
            errorDetail = errorObj["message"] as? String ?? errorObj["name"] as? String
        }
        return ProcessingInfo(
            state: state,
            checkAfterSecs: check,
            progressPercent: pct,
            errorDetail: errorDetail
        )
    }

    // MARK: - Create tweet (step 6)

    private func createTweet(
        text: String,
        mediaID: String,
        accessToken tokens: inout XTokens
    ) async throws -> String {
        let url = XConfig.apiBase.appendingPathComponent("tweets")
        let body: [String: Any] = [
            "text": text,
            "media": ["media_ids": [mediaID]],
        ]
        let data = try await authedJSONRequest(
            url: url,
            method: "POST",
            json: body,
            label: "tweets.create",
            accessToken: &tokens
        )
        guard let root = try JSONSerialization.jsonObject(with: data) as? [String: Any],
              let d = root["data"] as? [String: Any],
              let id = d["id"] as? String, !id.isEmpty else {
            throw ClientError.missingResponseField("data.id")
        }
        return id
    }

    // MARK: - Shared request helpers

    /// JSON POST/PUT/GET with bearer auth. Handles one 401 → refresh → retry.
    private func authedJSONRequest(
        url: URL,
        method: String,
        json: [String: Any]?,
        label: String,
        accessToken tokens: inout XTokens
    ) async throws -> Data {
        var request = URLRequest(url: url)
        request.httpMethod = method
        request.setValue("Bearer \(tokens.accessToken)", forHTTPHeaderField: "Authorization")
        if let json {
            request.setValue("application/json", forHTTPHeaderField: "Content-Type")
            request.httpBody = try JSONSerialization.data(withJSONObject: json)
        }

        let (data, response) = try await URLSession.shared.data(for: request)
        guard let http = response as? HTTPURLResponse else {
            throw ClientError.requestFailed(label, -1, "No HTTP response")
        }

        if http.statusCode == 401, tokens.refreshToken != nil {
            tokens = try await auth.refresh(using: tokens)
            request.setValue("Bearer \(tokens.accessToken)", forHTTPHeaderField: "Authorization")
            let (data2, response2) = try await URLSession.shared.data(for: request)
            guard let http2 = response2 as? HTTPURLResponse else {
                throw ClientError.requestFailed("\(label) (retry)", -1, "No HTTP response")
            }
            guard (200..<300).contains(http2.statusCode) else {
                let bodyStr = String(data: data2, encoding: .utf8) ?? "<non-utf8>"
                throw ClientError.requestFailed("\(label) (retry)", http2.statusCode, bodyStr)
            }
            return data2
        }

        guard (200..<300).contains(http.statusCode) else {
            let bodyStr = String(data: data, encoding: .utf8) ?? "<non-utf8>"
            throw ClientError.requestFailed(label, http.statusCode, bodyStr)
        }
        return data
    }

    private func authedGetRequest(
        url: URL,
        label: String,
        accessToken tokens: inout XTokens
    ) async throws -> Data {
        try await authedJSONRequest(
            url: url,
            method: "GET",
            json: nil,
            label: label,
            accessToken: &tokens
        )
    }

    // MARK: - Multipart helper

    /// Builds a multipart/form-data body with a single file part and optional
    /// text form fields.
    private static func multipartBody(
        boundary: String,
        fields: [(name: String, value: String)],
        fileField: (name: String, filename: String, contentType: String, data: Data)
    ) -> Data {
        var body = Data()
        let crlf = "\r\n"

        for field in fields {
            body.append("--\(boundary)\(crlf)".data(using: .utf8)!)
            body.append("Content-Disposition: form-data; name=\"\(field.name)\"\(crlf)\(crlf)".data(using: .utf8)!)
            body.append("\(field.value)\(crlf)".data(using: .utf8)!)
        }

        body.append("--\(boundary)\(crlf)".data(using: .utf8)!)
        body.append(
            "Content-Disposition: form-data; name=\"\(fileField.name)\"; filename=\"\(fileField.filename)\"\(crlf)"
                .data(using: .utf8)!
        )
        body.append("Content-Type: \(fileField.contentType)\(crlf)\(crlf)".data(using: .utf8)!)
        body.append(fileField.data)
        body.append(crlf.data(using: .utf8)!)

        body.append("--\(boundary)--\(crlf)".data(using: .utf8)!)
        return body
    }
}
